// 左侧菜单导航数据
export const leftNavList = [
	{
		title: '基础图形',
		icon: 'iconfont icon-shouye',
		isOpen: true,
		id: '1',
		children: [
			{
				icon: 'iconfont icon-fangkuang',
				name: '矩形',
				id: '11',
				componentType: 'v-rect',
				config: {
					x: 20,
					y: 50,
					width: 100,
					height: 100,
					fill: '#e6e6e6',
					shadowBlur: 0,
					draggable: true,
					name: '1',
				},
				form: [
					{
						type: 'input',
						label: '客户姓名',
						prop: 'name',
						placeholder: '请输入客户姓名',
						required: true,
						disabled: false,
					},
					{
						type: 'select',
						label: '性别',
						prop: 'sex',
						placeholder: '请选择性别',
						required: true,
						disabled: false,
						options: [
							{
								value: '0',
								label: '女',
							},
							{
								value: '1',
								label: '男',
							},
						],
					},
					{
						type: 'input',
						label: '员工编号',
						prop: 'number',
						placeholder: '请输入员工编号',
						required: true,
						disabled: false,
					},
					{
						type: 'input',
						label: '办公电话',
						prop: 'mobile',
						placeholder: '请输入办公电话',
						required: true,
						disabled: false,
					},
					{
						type: 'select',
						label: '权限分配',
						prop: 'role',
						placeholder: '请选择性别',
						required: true,
						disabled: false,
						options: [
							{
								value: '0',
								label: '编辑权限',
							},
							{
								value: '1',
								label: '删除权限',
							},
						],
					},
					{
						type: 'checkbox',
						label: '模块选择',
						prop: 'module',
						placeholder: '请选择模块',
						required: true,
						disabled: false,
					},
				],
			},
			{
				icon: 'iconfont icon-fuwenben',
				name: '文本',
				id: '12',
				componentType: 'v-text',
				config: {
					x: 20,
					y: 50,
					text: 'Some text on canvas',
					fontSize: 20,
					draggable: true,
					name: '1',
				},
				form: [
					{
						type: 'input',
						label: '等级',
						prop: 'grade',
						placeholder: '请输入等级',
						required: true,
						disabled: false,
					},
					{
						type: 'input',
						label: '登记密码',
						prop: 'password',
						placeholder: '请输入登记密码',
						required: true,
						disabled: false,
					},
				],
			},
		],
	},
	{
		title: '物流设备',
		isOpen: true,
		icon: 'iconfont icon-caijian',
		id: '2',
		children: [
			{
				icon: 'cabinet',
				name: '电控柜',
				id: '26',
				componentType: 'cabinet',
				config: {
					x: 20,
					y: 50,
					width: 50,
					height: 50,
					driveId: '',
					driveName: '',
					connectionState: 0,
					name: '1',
					rotation: 0,
					scaleX: 1,
					scaleY: 1,
					draggable: true,
				},
				form: [
					{
						type: 'input',
						label: '活动名称7',
						prop: 'name21',
					},
				],
			},
			{
				icon: 'convery-transverse',
				name: '输送线',
				id: '21',
				componentType: 'converyTransverse',
				config: {
					x: 20,
					y: 50,
					width: 50,
					height: 50,
					deviceNo: '1001',
					name: '1',
					rotation: 0,
					scaleX: 1,
					scaleY: 1,
					draggable: true,
				},
				form: [
					{
						type: 'input',
						label: '活动名称7',
						prop: 'name21',
					},
				],
			},
			{
				icon: 'convery-portrait',
				name: '输送线',
				id: '22',
				componentType: 'converyPortrait',
				config: {
					x: 20,
					y: 50,
					width: 50,
					height: 50,
					deviceNo: '1001',
					name: '1',
					rotation: 0,
					scaleX: 1,
					scaleY: 1,
					draggable: true,
				},
				form: [
					{
						type: 'input',
						label: '活动名称7',
						prop: 'name21',
					},
				],
			},
			{
				icon: 'convery-half-circle',
				name: '输送线',
				id: '23',
				componentType: 'converyHalfCircle',
				config: {
					x: 20,
					y: 50,
					width: 50,
					height: 50,
					deviceNo: '1001',
					name: '1',
					rotation: 0,
					scaleX: 1,
					scaleY: 1,
					draggable: true,
				},
				form: [
					{
						type: 'input',
						label: '活动名称7',
						prop: 'name21',
					},
				],
			},
			{
				icon: 'convery-1-4-circle',
				name: '输送线',
				id: '24',
				componentType: 'convery1/4Circle',
				config: {
					x: 20,
					y: 50,
					width: 50,
					height: 50,
					deviceNo: '1001',
					name: '1',
					rotation: 0,
					scaleX: 1,
					scaleY: 1,
					draggable: true,
				},
				form: [
					{
						type: 'input',
						label: '活动名称7',
						prop: 'name21',
					},
				],
			},
			{
				icon: 'goods-shelves',
				name: '货架',
				id: '27',
				componentType: 'goodsShelves',
				config: {
					x: 20,
					y: 50,
					width: 50,
					height: 50,
					name: '1',
					rotation: 0,
					scaleX: 1,
					scaleY: 1,
					draggable: true,
				},
			},
			{
				icon: 'stacker-crane',
				name: '堆垛机',
				id: '25',
				componentType: 'stackerCrane',
				config: {
					x: 20,
					y: 50,
					deviceNo: 'SC01',
					width: 80,
					height: 40,
					name: '1',
					rotation: 0,
					scaleX: 1,
					scaleY: 1,
					draggable: true,
				},
			},
		],
	},
];
